server:
  port: 9000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/db_dev_brothers_delivery

    #    dev-padrão
#    username: postgres
#    password: root

    #    dev-bruno
#    username: postgres
#    password: postg

    #    dev-scooby
    username: postgres
    password: root

    hikari:
      pool-name:  SpringBootJPAHikariCP
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      auto-commit: true

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
#    url:
#    user:
#    password:

  output:
    ansi:
      enabled: detect

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security.web: INFO
    com.zaxxer.hikari.HikariConfig: ERROR
    com.zaxxer.hikari: ERROR
    org.hibernate: ERROR
    hibernate.SQL: DEBUG
    hibernate.cache: DEBUG
    hibernate.stat: DEBUG

springdoc:
  swagger-ui:
    enabled: true

  api-docs:
    enabled: true
    path: /brothers-delivery-api-docs

###### extra settings ###############################################################

app:
  auth:
    tokens:
      jwt:
        secret: 1cbf61daa877c839e9d49c10f897d1d9e4ae7d615bb5ba29eeffa2560542e475a081e949f95259db1a29f8a38a7087dc619ea6d993f4bd9db89b503fdb657140
        expiration: 6048000000 #7 days

      refresh-token:
        expiration: 8640000000 #10 days

      reset-code:
        expiration: 300000 # 5 minutes

