server:
  port: 9000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username:
    password:
    driverClassName: org.postgresql.Driver

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

logging:
  level:
    org.springframework.security.web: INFO

app:
  auth:
    tokens:
      jwt:
        secret: 1cbf61daa877c839e9d49c10f897d1d9e4ae7d615bb5ba29eeffa2560542e475a081e949f95259db1a29f8a38a7087dc619ea6d993f4bd9db89b503fdb657140
        expiration: 6048000000 #7 days

      refresh-token:
        expiration: 8640000000 #10 days

      reset-code:
        expiration: 300000 # 5 minutes

